---
# tasks file for jenkins
- name: Running apt update
  apt:
    update_cache: true
- name: Installing Java
  apt:
    name: default-jdk
    state: latest

- name: Adding apt_key to the system
  apt_key: 
    url: "{{ jenkins_url }}"
- name: Configure Repository
  apt_repository: 
    repo: "{{ jenkins_repo }}"
- name: Running apt update
  apt:
    update_cache: true
- name: Installing Jenkins
  apt:
    name: jenkins
- name: Status check
  service:
    name: jenkines
